name: Daily Website Crawl Test

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # 调整为 UTC 时间每天 00:05 运行（对应北京时间 08:05）
    - cron: '5 0 * * *'

jobs:
  crawl-and-notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup timezone
      run: |
        # 设置时区为上海（确保日期计算准确）
        sudo timedatectl set-timezone Asia/Shanghai
        
    - name: Set up directory
      run: |
        # 创建带日期的目录（格式：webpages-YYYYMMDD）
        DIR_NAME="webpages-$(date +'%Y%m%d')"
        echo "DIR_NAME=$DIR_NAME" >> $GITHUB_ENV
        mkdir -p $DIR_NAME

    - name: Crawl website
      run: |
        # 使用 wget 镜像下载网站（递归下载，保持目录结构）
        wget --mirror \
             --convert-links \
             --adjust-extension \
             --page-requisites \
             --no-parent \
             --no-host-directories \
             --restrict-file-name=unix \
             -P $DIR_NAME \
             http://www.saoing.com/

    - name: Commit changes
      run: |
        # 配置 Git 用户信息
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # 添加、提交并推送更改
        git add $DIR_NAME
        git commit -m "Add daily crawl: $DIR_NAME"
        git push

    - name: Send Telegram notification
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        #TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        #TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}        
      run: |
        # 发送 Telegram 通知
        MESSAGE="✅ 网站抓取完成！%0A- 日期: $(date +'%Y-%m-%d')%0A- 目录: $DIR_NAME%0A- 仓库: https://github.com/$GITHUB_REPOSITORY"
        
        curl -s -X POST \
          "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_CHAT_ID}" \
          -d text="$MESSAGE"
          
